# settings.yaml

reference_types:
  book:
    template: "Author, <i>Title</i>, ed. Editor (PublicationInfoRaw), Pages (Reference)."
    fields:
      InitialCf: '^(?:cf\.\s*)?'
      Author: '\[(?P<Author>[^\]]+)\]'
      Title: ',\s*<i>(?P<Title>[^<]+)</i>'
      Editor: '(?:,\s*ed\.\s+(?P<Editor>[^,(]+))?'
      PublicationInfoRaw: '(?:\s*\((?P<PublicationInfoRaw>[^)]+)\))?'
      Pages: '(?:,\s*(?P<Pages>[\d\s-]+(?:\s*-\s*\d+)?))?'
      Reference: '(?:\s*\((?P<Reference>[^)]+)\))?(?:[.;])?'
    required_fields: ["Author", "Title"]

  journalArticle:
    template: "Author, "ArticleTitle," <i>JournalName</i> Volume, no. Issue (Date): Pages."
    fields:
      Author: '(?P<Author>[A-Z][A-Za-z\s.,]+(?:et al\.)?),'
      ArticleTitle: '"(?P<ArticleTitle>[^"]+)"' # Content within quotes
      JournalName: '<i>(?P<JournalName>[^<]+)</i>' # Content within <i></i>
      Volume: ', (?P<Volume>\d+),' # A number surrounded by commas
      Issue: 'no\.\s*(?P<Issue>\d+)' # "no. " followed by a number
      Date: '\((?P<Date>\d{4})\)' # (YYYY)
      Pages: ':\s*(?P<Pages>[\d\s-]+)\.' # number(s) with potential hyphens/spaces before a period
    required_fields: ["Author", "ArticleTitle", "JournalName", "Date", "Pages"]

  webPage:
    template: "Author, <i>PageTitle</i>, WebsiteName, PublisherPlatform, DatePublished, URL."
    fields:
      InitialCf: '^(?:cf\.\s*)?'
      Author: '\[(?P<Author>[^\]]+)\]'
      PageTitle: ',\s*<i>(?P<PageTitle>[^<]+)</i>,'
      WebsiteName: '\s*(?P<WebsiteName>[^,]+),'
      PublisherPlatform: '(?:\s*(?P<PublisherPlatform>[^,]+),)?' # Optional
      DatePublished: '\s*(?P<DatePublished>\w+\s\d{1,2},\s\d{4}),'
      URL: '\s*(?P<URL>https?://[^\s]+)\.'
    required_fields: ["Author", "PageTitle", "WebsiteName", "URL"]

  dictionaryEntry:
    template: "Author, "Term," in <i>DictionaryTitle</i> (Place: Publisher, Date)."
    fields:
      InitialCf: '^(?:cf\.\s*)?'
      Author: '\[(?P<Author>[^\]]+)\]' # Escaped brackets for YAML
      Term: ',\s*"(?P<Term>[^"]+)"'
      KeywordIn: ',\s*in\s+'
      DictionaryTitle: '<i>(?P<DictionaryTitle>[^<]+)</i>'
      Place: '(?:\s*\((?P<Place>[^:]+):)?' # Optional parentheses for place
      Publisher: '(?:\s*:\s*(?P<Publisher>[^,\)]+))?' # Optional publisher
      Date: '\s*(?P<Date>\d{4})\)(?:[.;])?' # Date inside parentheses
    required_fields: ["Author", "Term", "DictionaryTitle", "Date"]

  bookChapter:
    template: "Author, “<i>ChapterTitle</i>,” in BookTitle, Editor (Place: Publisher, Date), Pages (SectionReference)."
    fields:
      InitialCf: '^(?:cf\.\s*)?'
      Author: '\[(?P<Author>[^\]]+)\]' # Escaped brackets for YAML
      ChapterTitle: ',\s*“<i>(?P<ChapterTitle>[^<]+)</i>”' # Italics inside smart quotes
      KeywordIn: ',\s*in\s+'
      BookTitle: '(?P<BookTitle>[^,]+?),' 
      Editor: '(?:ed\.\s+(?P<Editor>[^,(]+),)?' # Optional editor
      Place: '(?:\s*\((?P<Place>[^:]+):)?'
      Publisher: '(?:\s*:\s*(?P<Publisher>[^,\)]+))?'
      Date: '\s*(?P<Date>\d{4})\)(?:[.;])?' 
      Pages: '(?:,\s*(?P<Pages>[\d-]+))?'
      SectionReference: '(?: \((?P<SectionReference>[^)]+)\))?\.'
    required_fields: ["Author", "ChapterTitle", "BookTitle", "Date"]

  itemInBook:
    template: "Author, "ItemTitle," in <i>BookTitle</i>, ed. Editor (PublicationInfoRaw), Page."
    fields:
      InitialCf: '^(?:cf\.\s*)?'
      Author: '\[(?P<Author>[^\]]+)\]'
      ItemTitle: ',\s*"(?P<ItemTitle>[^"]+)"'
      KeywordIn: ',\s*in\s+'
      BookTitle: '<i>(?P<BookTitle>[^<]+)</i>'
      Editor: '(?:,\s*ed\.\s+(?P<Editor>[^,(]+))?'
      PublicationInfoRaw: '(?:\s*\((?P<PublicationInfoRaw>[^)]+)\))?'
      Page: '(?:,\s*(?P<Page>\d+))?(?:[.;])?'
    required_fields: ["Author", "ItemTitle", "BookTitle"]

  periodicalPublication:
    template: "Author, "Title," Periodical, vol. Volume, Year, Pages, no. ParagraphNo."
    fields:
      InitialCf: '^(?:cf\.\s*)?'
      Author: '\[(?P<Author>[^\]]+)\]'
      Title: ',\s*"(?P<Title>[^"]+)",'
      Periodical: '\s*(?P<Periodical>[^,]+),'
      Volume: '\s*vol\.\s+(?P<Volume>[^,]+),'
      Year: '\s*(?P<Year>\d{4}),'
      Pages: '\s*(?P<Pages>[\d\s-]+(?:\s*-\s*\d+)?),' # Allow spaces in page ranges
      ParagraphNo: '\s*no\.\s*(?P<ParagraphNo>[^.]+)\.'
    required_fields: ["Author", "Title", "Periodical", "Volume", "Year", "Pages"]

  conferencePaper:
    template: "Author, "ArticleTitle," ConferenceName, ConferenceDate, Pages."
    fields:
      InitialCf: '^(?:cf\.\s*)?'
      Author: '\[(?P<Author>[^\]]+)\]'
      ArticleTitle: ',\s*"(?P<ArticleTitle>[^"]+)",'
      ConferenceName: '\s*(?P<ConferenceName>[^,]+),'
      ConferenceDate: '\s*(?P<ConferenceDate>\w+\s\d{1,2},\s\d{4}),'
      Pages: '\s*(?P<Pages>[\d\s-]+(?:\s*-\s*\d+)?)\.' # Allow spaces in page ranges
    required_fields: ["Author", "ArticleTitle", "ConferenceName", "ConferenceDate", "Pages"]

# Add more types as needed: bookSection, conferencePaper, forumPost, dictionaryEntry, interview, letter

special_classics:
  STh: "Thomas Aquinas, <i>Summa Theologiae</i>" # Example, user can add more
  DS: "Henricus Denzinger, Peter Hünermann (eds.), <i>Enchiridion symbolorum definitionum et declarationum de rebus fidei et morum</i>"
